version: '2'

services:
  sonarqube:
    build: .
    container_name: sonarqubev563-app
    environment:
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonar
      SONARQUBE_JDBC_URL: jdbc:mysql://mysql:3306/sonar?useUnicode=true&characterEncoding=utf8
    depends_on:
      - mysql
    ports:
      - "9000:9000"
    links:
      - mysql
    #volumes:
    #    - sonarqube-data:/opt/sonarqube
  mysql:
    image: mysql:5.6
    container_name: sonarqubev563-db
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: sonar
      MYSQL_PASSWORD: sonar
      MYSQL_DATABASE: sonar
    ports:
      - "3306:3306"

# docker volume create --name=sonarqube-data
#volumes:
#  sonarqube-data:
#    external: true


