version: '2'

services:
  sonarqube:
    build: .
    container_name: sonarqubev563-app
    environment:
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonar
      SONARQUBE_JDBC_URL: jdbc:h2:tcp://localhost:9092/sonar
    ports:
      - "9000:9000"


